###REGISTER
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "user777",
  "password": "pass777",
  "firstName": "777",
  "lastName": "777",
  "phone": "phone",
  "role": "USER"
}

###LOGIN
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "username",
  "password": "password"
}

###LOGIN2
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "user777",
  "password": "pass777"
}

###GETME
GET http://localhost:8080/users/me
Content-Type: application/json
Authorization: Basic user777 pass777

###EDIT USER
PATCH http://localhost:8080/users/me
Content-Type: application/json
Authorization: Basic username password

{
  "phone": "33333",
  "lastName": "Ivanov",
  "firstName": "Ivan",
  "email": "username",
  "id": 1
}

###SET PASS
POST http://localhost:8080/users/set_password
Content-Type: application/json
Authorization: Basic username password1

{
  "newPassword": "password1",
  "currentPassword": "password"
}

###EDIT IMAGE
PATCH http://localhost:8080/users/me/image
Content-Type: multipart/form-data; boundary=UserImageBoundary
Authorization: Basic username password

--UserImageBoundary
Content-Disposition: form-data; name="image"; filename="testImage.png"
Content-Type: image/png

< testImage.png
--UserImageBoundary

###GET ALL ADS
GET http://localhost:8080/ads
Content-Type: application/json
Authorization: Basic user777 pass777

###POST AD
POST http://localhost:8080/ads
Content-Type: multipart/form-data; boundary=AddAdBoundary
Authorization: Basic username password

--AddAdBoundary
Content-Disposition: form-data; name="image"; filename="testImage.png"
Content-Type: image/png

< testImage.png
--AddAdBoundary
Content-Disposition: form-data; name="properties"
Content-Type: application/json

{
  "description": "description",
  "price": 1234,
  "title": "title"
}
--AddAdBoundary

###GET AD BY ID
GET http://localhost:8080/ads/2
Content-Type: application/json
Authorization: Basic user777 pass777

###DELETE AD BY ID
DELETE http://localhost:8080/ads/3
Content-Type: application/json
Authorization: Basic username password

###EDIT AD BY ID
PATCH http://localhost:8080/ads/1
Content-Type: application/json
Authorization: Basic username password

{
  "description": "new description",
  "price": 7777,
  "title": "new title"
}

###GET MY ADS
GET http://localhost:8080/ads/me
Content-Type: application/json
Authorization: Basic username password

###EDIT AD'S IMAGE
PATCH http://localhost:8080/ads/1/image
Content-Type: multipart/form-data; boundary=NewAdImageBoundary
Authorization: Basic username password

--NewAdImageBoundary
Content-Disposition: form-data; name="image"; filename="testImage.png"
Content-Type: image/png

< testImage.png
--NewAdImageBoundary

###POST COMMENT BY AD ID
POST http://localhost:8080/ads/2/comments
Content-Type: application/json
Authorization: Basic user777 pass777

{
  "text": "first comment"
}

### GET COMMETS BY AD ID
GET http://localhost:8080/ads/2/comments
Authorization: Basic user777 pass777

### DELETE COMMENT BY ID
DELETE http://localhost:8080/ads/2/comments/3
Authorization: Basic username password

###EDIT COMMENT BY ID
PATCH http://localhost:8080/ads/2/comments/2
Content-Type: application/json
Authorization: Basic username password

{
  "author": 0,
  "authorImage": "string",
  "authorFirstName": "string",
  "createdAt": 0,
  "pk": 0,
  "text": "fgfjjf"
}